printf "Installing Chocolatey"
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
printf "Chocolatey installed"

printf "Installing Python 3.6.7"
choco install python --version 3.7.2 --install-directory 'C:\Python36'
printf "Python 3.6.7 installed"

printf "Installing virtualenv"
pip install virtualenv
printf "virtualenv installed"

printf "Installing virtualenvwrapper"
pip install virtualenvwrapper
printf "virtualenvwrapper installed"

printf "Installing virtualenvwrapper-win"
pip install virtualenvwrapper-win
printf "virtualenvwrapper-win installed"

printf "Creating vietualenv 'myenv'"
mkvirtualenv myenv
printf "'myenv' created"

printf "working on myenv"
workon myenv
printf "In myenv"

printf "Installing Requirements"
pip install -r requirements.txt
printf "Requirements installed"



#python "${script_name}.py" train 2>&1 | tee "${log_path}"
# printf "\n%s\n\n" "----- Done! -----"

# printf "%s\n" "----- Transforming images... -----"
# # It is normal to get errors on some of the images.
# # Can turn off the progress bar inside
# script_name="transform_images"
# log_path="${logs_dir_path}/${script_name}.log"
# python "${script_name}.py" 2>&1 | tee "${log_path}"
# printf "\n%s\n\n" "----- Done! -----"

# # Can be "svm"/"knn"/"logistic"
# model_name="svm"

# printf "%s\n" "----- Building model... -----"
# script_name="train_model"
# log_path="${logs_dir_path}/${script_name}.log"
# python "${script_name}.py" "${model_name}" train 2>&1 | tee "${log_path}"
# printf "\n%s\n\n" "----- Done! -----"

# printf "%s\n" "----- Generating testing image labels... -----"
# script_name="generate_images_labels"
# log_path="${logs_dir_path}/${script_name}.log"
# python "${script_name}.py" test train 2>&1 | tee "${log_path}"
# printf "\n%s\n\n" "----- Done! -----"

# printf "%s\n" "----- Predicting from file... -----"
# # It is normal to get errors on some of the images.
# script_name="predict_from_file"
# log_path="${logs_dir_path}/${script_name}.log"
# python "${script_name}.py" "${model_name}" train 2>&1 | tee "${log_path}"
# printf "\n%s\n\n" "----- Done! -----"

# # Delete the redundant log file sometimes generated by tee
# rm nul